services:
  cerve-redis:
    image: redis:alpine3.23
    container_name: cerve-redis
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD:-cerve}"]
    environment:
      REDISCLI_AUTH: ${REDIS_PASSWORD:-cerve}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - cerve-network
    volumes:
      - cerve-redis-data:/data
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
