name: bullky

include:
  # infrastructure services
  - ./services/postgresql/compose.yml
  - ./services/redis-cache/compose.yml
  - ./services/redis-queue/compose.yml

volumes:
  bullky-db-data:
    driver: local
    name: bullky-db-data
  bullky-cache-data:
    driver: local
    name: bullky-cache-data
  bullky-queue-data:
    driver: local
    name: bullky-queue-data

networks:
  bullky-network:
    driver: bridge
    name: bullky-network
