export const PRODUCT_NAMES = [
	"Wireless Mouse",
	"Mechanical Keyboard",
	"USB-C Hub",
	"27-inch Monitor",
	"Noise Cancelling Headphones",
	"HD Webcam",
	"Laptop Stand",
	"External SSD 1TB",
	"Portable Charger",
	"Bluetooth Speaker",
	"Smart Watch",
	"Fitness Tracker",
	"Gaming Chair",
	"Standing Desk",
	"Desk Lamp",
	"Ergonomic Mouse Pad",
	"Wireless Charger",
	"Phone Case",
	"Screen Protector",
	"HDMI Cable",
	"Power Strip",
	"Surge Protector",
	"Wi-Fi 6 Router",
	"Mesh Network Kit",
	"Smart Plug",
	"Smart Bulb",
	"Security Camera",
	"Video Doorbell",
	"Robot Vacuum",
	"Air Purifier",
	"Humidifier",
	"Space Heater",
	"Electric Kettle",
	"Coffee Maker",
	"Blender",
	"Toaster",
	"Air Fryer",
	"Multi-Cooker",
	"Stand Mixer",
	"Knife Set",
	"Cutting Board",
	"Water Bottle",
	"Yoga Mat",
	"Resistance Bands",
	"Dumbbell Set",
	"Jump Rope",
	"Backpack",
	"Travel Pillow",
	"Luggage Set",
	"Umbrella",
] as const;
