# ==========================================
# ====== Persistence Strategy (AOF Only)
# ==========================================
save ""
appendonly yes
appendfsync everysec

appendfilename "appendonly.aof"
appenddirname "appendonlydir"

auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 32mb

# ==========================================
# ====== Memory Management
# ==========================================
maxmemory 600mb
maxmemory-policy noeviction

# ==========================================
# ====== Background Memory Deallocation (Lazy Freeing)
# ==========================================
lazyfree-lazy-expire yes
lazyfree-lazy-eviction yes
lazyfree-lazy-server-del yes

# ==========================================
# ====== Security & Accidental Command Guards
# ==========================================
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""